---
- name: disable selinux
  selinux: state=disabled
  notify:
  - reboot
  - wait for server to come back
- meta: flush_handlers

- name: ping
  ping:

- name: install some packages
  dnf: name=htop,vim,gnome-terminal,gedit state=present
