---
- name: disable selinux
  selinux: state=disabled
  notify:
  - reboot
  - wait for server to come back
- meta: flush_handlers

- name: ping
  ping:

- name: install some packages
  dnf: name=htop,vim,gnome-terminal,gedit,git state=present

- name: configure sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel\s'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
